name: Chroma Typescript Client Integration Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - '**'
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: TS Client Test
      run: bin/ts-integration-test
